# RavenPets Configuration

# Database settings
database:
  type: sqlite # or mysql
  # MySQL settings (only needed if database.type is mysql)
  host: localhost
  port: 3306
  database: ravenpets
  username: root
  password: password

# General settings
auto-spawn-on-join: true
follow-player: true
follow-distance: 3.0
follow-teleport-distance: 20.0

# Experience settings
exp-per-mob-kill: 10
exp-per-player-kill: 50
exp-per-block-mine: 1
exp-multiplier: 1.0

# Economy settings
enable-economy: true
coin-per-mob-kill: 1
coin-per-player-kill: 5
coin-multiplier: 1.0

# Shop settings
shop:
  xp-boost:
    cost: 100
    multiplier: 1.5
    duration: 3600 # in seconds
  coin-boost:
    cost: 100
    multiplier: 1.5
    duration: 3600 # in seconds
  custom-colors:
    cost: 500
  custom-particles:
    cost: 1000