# RavenPets Configuration

# Database settings
database:
  type: sqlite # or mysql
  # MySQL settings (only needed if database.type is mysql)
  host: localhost
  port: 3306
  database: ravenpets
  username: root
  password: password

# General settings
auto-spawn-on-join: true
follow-player: true
follow-distance: 3.0
follow-teleport-distance: 20.0

# Experience settings
exp-per-mob-kill: 10
exp-per-player-kill: 50
exp-per-block-mine: 1
exp-multiplier: 1.0

# Economy settings
enable-economy: true
coin-per-mob-kill: 1
coin-per-player-kill: 5
coin-multiplier: 1.0

# Theme settings
raven-theme:
  primary-color: "#9c27b0" # Purple
  secondary-color: "#e91e63" # Pink
  background-color: "#212121" # Dark

# Ability settings
abilities:
  fire:
    cooldown: 60 # in seconds
    secondary-cooldown: 120 # in seconds
    pvp-damage: true
  water:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  earth:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  air:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  lightning:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  ice:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  nature:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  darkness:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  light:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true

# Shop settings
shop:
  xp-boost:
    cost: 100
    multiplier: 1.5
    duration: 3600 # in seconds
  coin-boost:
    cost: 100
    multiplier: 1.5
    duration: 3600 # in seconds
  custom-colors:
    cost: 500
  custom-particles:
    cost: 1000

# Messages
messages:
  prefix: "&5&l[RavenPets] &r"
  raven-spawned: "&dYour raven has been spawned!"
  raven-despawned: "&dYour raven has been despawned!"
  level-up: "&d&lYour raven leveled up to level &f%level%&d&l!"
  tier-up: "&5&l⚡ Your raven advanced to tier &f%tier%&5&l! ⚡"
  ability-cooldown: "&c&lAbility on cooldown! &7(&f%seconds%s &7remaining)"
  secondary-ability-cooldown: "&c&lSecondary ability on cooldown! &7(&f%seconds%s &7remaining)"
  ability-activated: "%color%%ability% &r&7activated!"
  secondary-ability-activated: "%color%%ability% &r&7unleashed!"
  rename-prompt: "&d&lType your desired raven name in chat:"
  rename-success: "&d&lYour raven has been renamed to &r%name%&d&l!"
  rename-too-long: "&c&lRaven name cannot be longer than 16 characters!"
  rename-no-color-perm: "&c&lYou don't have permission to use color codes in your raven's name!"