# RavenPets Configuration

# Database settings
database:
  type: sqlite # or mysql
  # MySQL settings (only needed if database.type is mysql)
  host: localhost
  port: 3306
  database: ravenpets
  username: root
  password: password

# General settings
auto-spawn-on-join: true
follow-player: true
follow-distance: 3.0
follow-teleport-distance: 20.0

# Experience settings
exp-per-mob-kill: 10
exp-per-player-kill: 50
exp-per-block-mine: 1
exp-multiplier: 1.0

# Economy settings
enable-economy: true
coin-per-mob-kill: 1
coin-per-player-kill: 5
coin-multiplier: 1.0

# GUI settings
gui:
  title-prefix: "§5§l⚜"
  enable-animations: true
  auto-refresh: true

# Theme settings
raven-theme:
  primary-color: "#9c27b0" # Purple
  secondary-color: "#e91e63" # Pink
  background-color: "#212121" # Dark

# Ability settings
abilities:
  fire:
    cooldown: 60 # in seconds
    secondary-cooldown: 120 # in seconds
    pvp-damage: true
  water:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  earth:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  air:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  lightning:
    cooldown: 45
    secondary-cooldown: 90
    pvp-damage: true
  ice:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  nature:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  darkness:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true
  light:
    cooldown: 60
    secondary-cooldown: 120
    pvp-damage: true

# Ability damage scaling
ability-damage:
  novice: 1.0
  adept: 1.5
  expert: 2.0
  master: 2.5
  legendary: 3.0

# Shop settings
shop:
  xp-boost:
    cost: 100
    multiplier: 1.5
    duration: 3600 # in seconds (1 hour)
  coin-boost:
    cost: 100
    multiplier: 1.5
    duration: 3600 # in seconds (1 hour)
  custom-colors:
    cost: 500
    description: "Make your raven display element-specific colors"
  custom-particles:
    cost: 1000
    description: "Add enhanced particle effects to your raven"
  element-change:
    enabled: true
    cost: 2000
    description: "Change your raven's element type"
  tier-boost:
    enabled: false # Disabled by default - only through leveling
    cost: 5000
    description: "Boost your raven's tier by one level"

# Element boost settings
# These add multipliers to specific environments
element-boosts:
  fire:
    in-nether: 1.5
    in-desert: 1.2
  water:
    in-ocean: 1.5
    in-rain: 1.3
  earth:
    underground: 1.3
    in-mountains: 1.2
  air:
    above-y-100: 1.3
    in-sky: 1.5
  lightning:
    in-thunderstorm: 2.0
  ice:
    in-snow: 1.5
    in-cold-biome: 1.3
  nature:
    in-forest: 1.5
    in-jungle: 1.3
  darkness:
    at-night: 1.3
    underground: 1.2
  light:
    in-daylight: 1.3
    in-end: 1.2

# Messages
messages:
  prefix: "&5&l[RavenPets] &r"
  raven-spawned: "&dYour raven has been spawned!"
  raven-despawned: "&dYour raven has been despawned!"
  level-up: "&d&lYour raven leveled up to level &f%level%&d&l!"
  tier-up: "&5&l⚡ Your raven advanced to tier &f%tier%&5&l! ⚡"
  ability-cooldown: "&c&lAbility on cooldown! &7(&f%seconds%s &7remaining)"
  secondary-ability-cooldown: "&c&lSecondary ability on cooldown! &7(&f%seconds%s &7remaining)"
  ability-activated: "%color%%ability% &r&7activated!"
  secondary-ability-activated: "%color%%ability% &r&7unleashed!"
  rename-prompt: "&d&lType your desired raven name in chat:"
  rename-success: "&d&lYour raven has been renamed to &r%name%&d&l!"
  rename-too-long: "&c&lRaven name cannot be longer than 16 characters!"
  rename-no-color-perm: "&c&lYou don't have permission to use color codes in your raven's name!"

  # GUI related messages
  gui-main-title: "&5&l⚜ Raven Menu ⚜"
  gui-abilities-title: "&5&l⚜ Raven Abilities ⚜"
  gui-stats-title: "&5&l⚜ Raven Statistics ⚜"
  gui-customization-title: "&5&l⚜ Raven Customization ⚜"

  # Element descriptions for GUI
  element-fire-desc: "&cFire&7 embodies destruction and power, burning through obstacles with intense heat."
  element-water-desc: "&9Water&7 flows with adaptability and healing, providing sustenance and protection."
  element-earth-desc: "&2Earth&7 represents stability and strength, standing firm against all challenges."
  element-air-desc: "&fAir&7 brings freedom and swiftness, allowing movement unhindered by boundaries."
  element-lightning-desc: "&eLightning&7 strikes with speed and precision, channeling raw elemental energy."
  element-ice-desc: "&bIce&7 freezes and preserves, slowing enemies and creating protective barriers."
  element-nature-desc: "&aNature&7 grows and nurtures, controlling the living forces of plants and life."
  element-darkness-desc: "&8Darkness&7 conceals and obscures, wielding shadow to confuse and terrify."
  element-light-desc: "&eLight&7 illuminates and purifies, healing allies and smiting undead foes."

# Advanced settings
debug-mode: false
auto-save-interval: 6000 # in ticks (5 minutes)
max-ravens-per-player: 1